### ISSUE TITLE
PROCESS CHANGE: Writers or WG leads should get admin powers to repos

### ISSUE THREAD

**Issue by Cali0707** [knative/community#1570]
From [discussion on slack](https://cloud-native.slack.com/archives/C04LMU33V1S/p1715612445608609?thread_ts=1715609483.903239&cid=C04LMU33V1S), it would be nice for writers (or at least the WG leads) for various areas to be able to do admin-only actions such as `/override` various tests on a PR. 

## Expected benefits

Fewer calls to TOC members to `/override` on PRs, and no need to wait on someone else when something needs to be overriden.

## Expected costs

More people will be admins on repos

**Comment by dsimansk** [comment]
/cc @knative/productivity-leads 

Hi folks, is there a viable way to handle such request via Peribolos config?

**Comment by Cali0707** [comment]
@dsimansk one way I could think of doing this is, for each repo where currently there is the `write` permission, changing that to `admin`. For example, for the eventing writers group we could change the config to:
```yaml
Eventing Writers:
        description: Grants write access to eventing-related repositories.
        privacy: closed
        repos:
          eventing: admin
          eventing-contrib: admin
          pkg: admin
          release: admin
```
