### ISSUE TITLE
Hello World - Rust(community/samples/serving/helloworld-rust/index.md) Updated hello world example

### ISSUE THREAD

**Issue by 06chaynes** [knative/community#533]
The example provided uses an older version of hyper (0.12), I thought I'd provide a version built against the latest version at this time (0.14). I also received an error from cargo install about needing to specify a path so I also updated the example Dockerfile.

Cargo.toml

```toml
[package]
name = "hellorust"
version = "0.0.1"
publish = false

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
pretty_env_logger = "0.4"
```

main.src

```rust
use hyper::{
    server::conn::AddrStream,
    service::{make_service_fn, service_fn},
    Body, Request, Response, Server,
};
use std::convert::Infallible;
use std::env;

#[tokio::main]
async fn main() {
    pretty_env_logger::init();

    let mut port: u16 = 8080;
    match env::var("PORT") {
        Ok(p) => {
            match p.parse::<u16>() {
                Ok(n) => {
                    port = n;
                }
                Err(_e) => {}
            };
        }
        Err(_e) => {}
    };
    let addr = ([0, 0, 0, 0], port).into();

    let make_svc = make_service_fn(|_socket: &AddrStream| async move {
        Ok::<_, Infallible>(service_fn(move |_: Request<Body>| async move {
            let mut hello = "Hello ".to_string();
            match env::var("TARGET") {
                Ok(target) => {
                    hello.push_str(&target);
                }
                Err(_e) => hello.push_str("World"),
            };
            Ok::<_, Infallible>(Response::new(Body::from(hello)))
        }))
    });

    let server = Server::bind(&addr).serve(make_svc);

    println!("Listening on http://{}", addr);
    if let Err(e) = server.await {
        eprintln!("server error: {}", e);
    }
}
```

Dockerfile

```dockerfile
# Use the official Rust image.
# https://hub.docker.com/_/rust
FROM rust:1.50.0

# Copy local code to the container image.
WORKDIR /usr/src/app
COPY . .

# Install production dependencies and build a release artifact.
RUN cargo install --path .

# Run the web service on container startup.
CMD ["hellorust"]
```
